Vushop\AdminBundle\Entity\Image:
    type: entity
    table: image
    id:
        imageId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: image_id
            generator:
                strategy: IDENTITY
    fields:
        imageName:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: image_name
        imageUrl:
            type: string
            nullable: false
            length: 500
            fixed: false
            comment: ''
            column: image_url
        productId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: product_id
        status:
            type: boolean
            nullable: true
            comment: '0: inactive, 1: active'
    lifecycleCallbacks: {  }
