Vushop\AdminBundle\Entity\Slideshow:
    type: entity
    table: slideshow
    id:
        slideshowId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: slideshow_id
            generator:
                strategy: IDENTITY
    fields:
        itemName:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: item_name
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        imageUrl:
            type: string
            nullable: false
            length: 500
            fixed: false
            comment: ''
            column: image_url
        url:
            type: string
            nullable: false
            length: 500
            fixed: false
            comment: ''
        createdDate:
            type: datetime
            nullable: true
            comment: ''
            column: created_date
        updatedDate:
            type: datetime
            nullable: true
            comment: ''
            column: updated_date
    lifecycleCallbacks: {  }
