parameters:
#    admin.example.class: Vushop\AdminBundle\Example

services:
#    admin.example:
#        class: %admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    common.twig.extension:
        class: Vushop\AdminBundle\Twig\Extensions\CommonExtension
        arguments: [ @service_container, @router]
        tags:
          - { name: twig.extension }
